repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      # - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: fix-encoding-pragma
        args: [--remove]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: (get-poetry.py)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       exclude: ^(docs/|example-plugin/|tests/conftest)|(get-poetry.py)
  #       args: [--explicit-package-bases]
